title: Sungjin Nam
email: sungjinnam@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Sungjin Nam, Senior Research Scientist specializing in NLP and ML for Educational Technology
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/